### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by klzsysy** [aylei/kubectl-debug#35]
网络情况：通过apiservice接口访问远程集群

配置：
```yaml
# debug-agent 映射到宿主机的端口
# 默认 10027
agentPort: 10027

# 是否开启ageless模式
# 默认 false
agentless: false
# agentPod 的 namespace, agentless模式可用
# 默认 default
agentPodNamespace: kube-system
# agentPod 的名称前缀，后缀是目的主机名, agentless模式可用
# 默认 debug-agent-pod
agentPodNamePrefix: debug-agent-pod
# agentPod 的镜像, agentless模式可用
# 默认 aylei/debug-agent:latest
agentImage: aylei/debug-agent:latest

# debug-agent DaemonSet 的名字, port-forward 模式时会用到
# 默认 'debug-agent'
debugAgentDaemonset: debug-agent
# debug-agent DaemonSet 的 namespace, port-forward 模式会用到
# 默认 'default'
debugAgentNamespace: kube-system
# 是否开启 port-forward 模式
# 默认 false
portForward: true
# image of the debug container
# default as showed
image: nicolaka/netshoot:latest
# start command of the debug container
# default ['bash']
command:
- '/bin/bash'
- '-l'
```

效果：
```sh
➜  ~ kubectl debug -n runtime  gateway-controller-7989c46dff-msdzh  bash
error parsing configuration file: yaml: unmarshal errors:
  line 7: field agentless not found in type plugin.Config
  line 10: field agentPodNamespace not found in type plugin.Config
  line 13: field agentPodNamePrefix not found in type plugin.Config
  line 16: field agentImage not found in type plugin.Config
```

然后卡死

使用README中的命令也无效
```sh
➜  ~ kubectl debug -n runtime gateway-controller-7989c46dff-msdzh --port-forward --daemonset-ns=kube-system --daemonset-name=debug-agent
Error: unknown flag: --port-forward
```

(摊手
